"""create account table

Revision ID: eb152e0ce217
Revises: 
Create Date: 2024-09-19 16:50:33.130605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb152e0ce217'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('T_ACCOUNT',
    sa.Column('ACCOUNT_NUMBER', sa.String(), nullable=False),
    sa.Column('API_KEY', sa.String(), nullable=False),
    sa.Column('ACCESS_TOKEN', sa.String(), nullable=False),
    sa.Column('PRODUCT_ID', sa.String(), nullable=True),
    sa.Column('CR_DT', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('ACCOUNT_NUMBER', 'API_KEY')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('T_ACCOUNT')
    # ### end Alembic commands ###
